version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  
  app:
    depends_on:
      - "mariadb"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/pearson
      - gems:/gems
 
volumes:
  mariadb:
  gems:
